class_name PredicateBase extends Node

enum REQUESTTYPE
{INVENTORY_REMOVE,
INVENTORY_MOVE, 
INVENTORY_TRANSFER,
INVENTORY_DROP, 
INVENTORY_PICKUP,
INVENTORY_DELETE, 
INVENTORY_OPEN,
INVENTORY_CLOSE}

enum CHECKTYPE{
	DISTANCE,
	OWNERSHIP
}
